// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocal.proto

package per.johnson.server.protocal;

import java.util.UUID;

public final class ProtocalOuterClass {
    private ProtocalOuterClass() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface ProtocalOrBuilder extends
            // @@protoc_insertion_point(interface_extends:per.johnson.server.protocal.Protocal)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bool bridge = 1;</code>
         */
        boolean getBridge();

        /**
         * <code>int32 type = 2;</code>
         */
        int getType();

        /**
         * <code>string dataContent = 3;</code>
         */
        java.lang.String getDataContent();
        /**
         * <code>string dataContent = 3;</code>
         */
        com.google.protobuf.ByteString
        getDataContentBytes();

        /**
         * <code>string from = 4;</code>
         */
        java.lang.String getFrom();
        /**
         * <code>string from = 4;</code>
         */
        com.google.protobuf.ByteString
        getFromBytes();

        /**
         * <code>string to = 5;</code>
         */
        java.lang.String getTo();
        /**
         * <code>string to = 5;</code>
         */
        com.google.protobuf.ByteString
        getToBytes();

        /**
         * <code>string fp = 6;</code>
         */
        java.lang.String getFp();
        /**
         * <code>string fp = 6;</code>
         */
        com.google.protobuf.ByteString
        getFpBytes();

        /**
         * <code>bool QoS = 7;</code>
         */
        boolean getQoS();

        /**
         * <code>int32 typeu = 8;</code>
         */
        int getTypeu();
    }
    /**
     * Protobuf type {@code per.johnson.server.protocal.Protocal}
     */
    public  static final class Protocal extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:per.johnson.server.protocal.Protocal)
            ProtocalOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Protocal.newBuilder() to construct.
        private Protocal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Protocal() {
            bridge_ = false;
            type_ = 0;
            dataContent_ = "";
            from_ = "";
            to_ = "";
            fp_ = "";
            qoS_ = false;
            typeu_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Protocal(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            bridge_ = input.readBool();
                            break;
                        }
                        case 16: {

                            type_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            dataContent_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            from_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            to_ = s;
                            break;
                        }
                        case 50: {
                            java.lang.String s = input.readStringRequireUtf8();

                            fp_ = s;
                            break;
                        }
                        case 56: {

                            qoS_ = input.readBool();
                            break;
                        }
                        case 64: {

                            typeu_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return per.johnson.server.protocal.ProtocalOuterClass.internal_static_per_johnson_server_protocal_Protocal_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return per.johnson.server.protocal.ProtocalOuterClass.internal_static_per_johnson_server_protocal_Protocal_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            per.johnson.server.protocal.ProtocalOuterClass.Protocal.class, per.johnson.server.protocal.ProtocalOuterClass.Protocal.Builder.class);
        }

        public static final int BRIDGE_FIELD_NUMBER = 1;
        private boolean bridge_;
        /**
         * <code>bool bridge = 1;</code>
         */
        public boolean getBridge() {
            return bridge_;
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private int type_;
        /**
         * <code>int32 type = 2;</code>
         */
        public int getType() {
            return type_;
        }

        public static final int DATACONTENT_FIELD_NUMBER = 3;
        private volatile java.lang.Object dataContent_;
        /**
         * <code>string dataContent = 3;</code>
         */
        public java.lang.String getDataContent() {
            java.lang.Object ref = dataContent_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dataContent_ = s;
                return s;
            }
        }
        /**
         * <code>string dataContent = 3;</code>
         */
        public com.google.protobuf.ByteString
        getDataContentBytes() {
            java.lang.Object ref = dataContent_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dataContent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FROM_FIELD_NUMBER = 4;
        private volatile java.lang.Object from_;
        /**
         * <code>string from = 4;</code>
         */
        public java.lang.String getFrom() {
            java.lang.Object ref = from_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                from_ = s;
                return s;
            }
        }
        /**
         * <code>string from = 4;</code>
         */
        public com.google.protobuf.ByteString
        getFromBytes() {
            java.lang.Object ref = from_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                from_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TO_FIELD_NUMBER = 5;
        private volatile java.lang.Object to_;
        /**
         * <code>string to = 5;</code>
         */
        public java.lang.String getTo() {
            java.lang.Object ref = to_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                to_ = s;
                return s;
            }
        }
        /**
         * <code>string to = 5;</code>
         */
        public com.google.protobuf.ByteString
        getToBytes() {
            java.lang.Object ref = to_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                to_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FP_FIELD_NUMBER = 6;
        private volatile java.lang.Object fp_;
        /**
         * <code>string fp = 6;</code>
         */
        public java.lang.String getFp() {
            java.lang.Object ref = fp_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                fp_ = s;
                return s;
            }
        }
        /**
         * <code>string fp = 6;</code>
         */
        public com.google.protobuf.ByteString
        getFpBytes() {
            java.lang.Object ref = fp_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                fp_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int QOS_FIELD_NUMBER = 7;
        private boolean qoS_;
        /**
         * <code>bool QoS = 7;</code>
         */
        public boolean getQoS() {
            return qoS_;
        }

        public static final int TYPEU_FIELD_NUMBER = 8;
        private int typeu_;
        /**
         * <code>int32 typeu = 8;</code>
         */
        public int getTypeu() {
            return typeu_;
        }

        /**
         * 自定义代码
         */
        private int retryCount=1;
        public int getRetryCount(){
            return retryCount;
        }
        public void increaseRetryCount(){
            this.retryCount++;
        }
        public Protocal clone(){
            Protocal protocal= Protocal.newBuilder(this).build();
            protocal.retryCount = this.retryCount;
            return protocal;
        }
        public byte[] toBytes() {
            return this.toByteArray();
        }
        public static String genFingerPrint(){
            return UUID.randomUUID().toString();//System.currentTimeMillis();
        }
        /**
         * 自定义代码结束
         */

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (bridge_ != false) {
                output.writeBool(1, bridge_);
            }
            if (type_ != 0) {
                output.writeInt32(2, type_);
            }
            if (!getDataContentBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataContent_);
            }
            if (!getFromBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, from_);
            }
            if (!getToBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, to_);
            }
            if (!getFpBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fp_);
            }
            if (qoS_ != false) {
                output.writeBool(7, qoS_);
            }
            if (typeu_ != 0) {
                output.writeInt32(8, typeu_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (bridge_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, bridge_);
            }
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, type_);
            }
            if (!getDataContentBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataContent_);
            }
            if (!getFromBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, from_);
            }
            if (!getToBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, to_);
            }
            if (!getFpBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fp_);
            }
            if (qoS_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(7, qoS_);
            }
            if (typeu_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(8, typeu_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof per.johnson.server.protocal.ProtocalOuterClass.Protocal)) {
                return super.equals(obj);
            }
            per.johnson.server.protocal.ProtocalOuterClass.Protocal other = (per.johnson.server.protocal.ProtocalOuterClass.Protocal) obj;

            boolean result = true;
            result = result && (getBridge()
                    == other.getBridge());
            result = result && (getType()
                    == other.getType());
            result = result && getDataContent()
                    .equals(other.getDataContent());
            result = result && getFrom()
                    .equals(other.getFrom());
            result = result && getTo()
                    .equals(other.getTo());
            result = result && getFp()
                    .equals(other.getFp());
            result = result && (getQoS()
                    == other.getQoS());
            result = result && (getTypeu()
                    == other.getTypeu());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + BRIDGE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getBridge());
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (37 * hash) + DATACONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getDataContent().hashCode();
            hash = (37 * hash) + FROM_FIELD_NUMBER;
            hash = (53 * hash) + getFrom().hashCode();
            hash = (37 * hash) + TO_FIELD_NUMBER;
            hash = (53 * hash) + getTo().hashCode();
            hash = (37 * hash) + FP_FIELD_NUMBER;
            hash = (53 * hash) + getFp().hashCode();
            hash = (37 * hash) + QOS_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getQoS());
            hash = (37 * hash) + TYPEU_FIELD_NUMBER;
            hash = (53 * hash) + getTypeu();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(per.johnson.server.protocal.ProtocalOuterClass.Protocal prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }



        /**
         * Protobuf type {@code per.johnson.server.protocal.Protocal}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:per.johnson.server.protocal.Protocal)
                per.johnson.server.protocal.ProtocalOuterClass.ProtocalOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return per.johnson.server.protocal.ProtocalOuterClass.internal_static_per_johnson_server_protocal_Protocal_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return per.johnson.server.protocal.ProtocalOuterClass.internal_static_per_johnson_server_protocal_Protocal_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                per.johnson.server.protocal.ProtocalOuterClass.Protocal.class, per.johnson.server.protocal.ProtocalOuterClass.Protocal.Builder.class);
            }

            // Construct using per.johnson.server.protocal.ProtocalOuterClass.Protocal.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                bridge_ = false;

                type_ = 0;

                dataContent_ = "";

                from_ = "";

                to_ = "";

                fp_ = "";

                qoS_ = false;

                typeu_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return per.johnson.server.protocal.ProtocalOuterClass.internal_static_per_johnson_server_protocal_Protocal_descriptor;
            }

            public per.johnson.server.protocal.ProtocalOuterClass.Protocal getDefaultInstanceForType() {
                return per.johnson.server.protocal.ProtocalOuterClass.Protocal.getDefaultInstance();
            }

            public per.johnson.server.protocal.ProtocalOuterClass.Protocal build() {
                per.johnson.server.protocal.ProtocalOuterClass.Protocal result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public per.johnson.server.protocal.ProtocalOuterClass.Protocal buildPartial() {
                per.johnson.server.protocal.ProtocalOuterClass.Protocal result = new per.johnson.server.protocal.ProtocalOuterClass.Protocal(this);
                result.bridge_ = bridge_;
                result.type_ = type_;
                result.dataContent_ = dataContent_;
                result.from_ = from_;
                result.to_ = to_;
                result.fp_ = fp_;
                result.qoS_ = qoS_;
                result.typeu_ = typeu_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof per.johnson.server.protocal.ProtocalOuterClass.Protocal) {
                    return mergeFrom((per.johnson.server.protocal.ProtocalOuterClass.Protocal)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(per.johnson.server.protocal.ProtocalOuterClass.Protocal other) {
                if (other == per.johnson.server.protocal.ProtocalOuterClass.Protocal.getDefaultInstance()) return this;
                if (other.getBridge() != false) {
                    setBridge(other.getBridge());
                }
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (!other.getDataContent().isEmpty()) {
                    dataContent_ = other.dataContent_;
                    onChanged();
                }
                if (!other.getFrom().isEmpty()) {
                    from_ = other.from_;
                    onChanged();
                }
                if (!other.getTo().isEmpty()) {
                    to_ = other.to_;
                    onChanged();
                }
                if (!other.getFp().isEmpty()) {
                    fp_ = other.fp_;
                    onChanged();
                }
                if (other.getQoS() != false) {
                    setQoS(other.getQoS());
                }
                if (other.getTypeu() != 0) {
                    setTypeu(other.getTypeu());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                per.johnson.server.protocal.ProtocalOuterClass.Protocal parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (per.johnson.server.protocal.ProtocalOuterClass.Protocal) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private boolean bridge_ ;
            /**
             * <code>bool bridge = 1;</code>
             */
            public boolean getBridge() {
                return bridge_;
            }
            /**
             * <code>bool bridge = 1;</code>
             */
            public Builder setBridge(boolean value) {

                bridge_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bool bridge = 1;</code>
             */
            public Builder clearBridge() {

                bridge_ = false;
                onChanged();
                return this;
            }

            private int type_ ;
            /**
             * <code>int32 type = 2;</code>
             */
            public int getType() {
                return type_;
            }
            /**
             * <code>int32 type = 2;</code>
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 type = 2;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object dataContent_ = "";
            /**
             * <code>string dataContent = 3;</code>
             */
            public java.lang.String getDataContent() {
                java.lang.Object ref = dataContent_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    dataContent_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string dataContent = 3;</code>
             */
            public com.google.protobuf.ByteString
            getDataContentBytes() {
                java.lang.Object ref = dataContent_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    dataContent_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string dataContent = 3;</code>
             */
            public Builder setDataContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                dataContent_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string dataContent = 3;</code>
             */
            public Builder clearDataContent() {

                dataContent_ = getDefaultInstance().getDataContent();
                onChanged();
                return this;
            }
            /**
             * <code>string dataContent = 3;</code>
             */
            public Builder setDataContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                dataContent_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object from_ = "";
            /**
             * <code>string from = 4;</code>
             */
            public java.lang.String getFrom() {
                java.lang.Object ref = from_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    from_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string from = 4;</code>
             */
            public com.google.protobuf.ByteString
            getFromBytes() {
                java.lang.Object ref = from_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    from_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string from = 4;</code>
             */
            public Builder setFrom(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                from_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string from = 4;</code>
             */
            public Builder clearFrom() {

                from_ = getDefaultInstance().getFrom();
                onChanged();
                return this;
            }
            /**
             * <code>string from = 4;</code>
             */
            public Builder setFromBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                from_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object to_ = "";
            /**
             * <code>string to = 5;</code>
             */
            public java.lang.String getTo() {
                java.lang.Object ref = to_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    to_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string to = 5;</code>
             */
            public com.google.protobuf.ByteString
            getToBytes() {
                java.lang.Object ref = to_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    to_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string to = 5;</code>
             */
            public Builder setTo(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                to_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string to = 5;</code>
             */
            public Builder clearTo() {

                to_ = getDefaultInstance().getTo();
                onChanged();
                return this;
            }
            /**
             * <code>string to = 5;</code>
             */
            public Builder setToBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                to_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object fp_ = "";
            /**
             * <code>string fp = 6;</code>
             */
            public java.lang.String getFp() {
                java.lang.Object ref = fp_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    fp_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string fp = 6;</code>
             */
            public com.google.protobuf.ByteString
            getFpBytes() {
                java.lang.Object ref = fp_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    fp_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string fp = 6;</code>
             */
            public Builder setFp(
                    java.lang.String value) {
                if (value == null) {
                    //不传入fg，重新构造
                    value = genFingerPrint();
                    //throw new NullPointerException();
                }

                fp_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string fp = 6;</code>
             */
            public Builder clearFp() {

                fp_ = getDefaultInstance().getFp();
                onChanged();
                return this;
            }
            /**
             * <code>string fp = 6;</code>
             */
            public Builder setFpBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                fp_ = value;
                onChanged();
                return this;
            }

            private boolean qoS_ ;
            /**
             * <code>bool QoS = 7;</code>
             */
            public boolean getQoS() {
                return qoS_;
            }
            /**
             * <code>bool QoS = 7;</code>
             */
            public Builder setQoS(boolean value) {

                qoS_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bool QoS = 7;</code>
             */
            public Builder clearQoS() {

                qoS_ = false;
                onChanged();
                return this;
            }

            private int typeu_ ;
            /**
             * <code>int32 typeu = 8;</code>
             */
            public int getTypeu() {
                return typeu_;
            }
            /**
             * <code>int32 typeu = 8;</code>
             */
            public Builder setTypeu(int value) {

                typeu_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 typeu = 8;</code>
             */
            public Builder clearTypeu() {

                typeu_ = 0;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:per.johnson.server.protocal.Protocal)
        }

        // @@protoc_insertion_point(class_scope:per.johnson.server.protocal.Protocal)
        private static final per.johnson.server.protocal.ProtocalOuterClass.Protocal DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new per.johnson.server.protocal.ProtocalOuterClass.Protocal();
        }

        public static per.johnson.server.protocal.ProtocalOuterClass.Protocal getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Protocal>
                PARSER = new com.google.protobuf.AbstractParser<Protocal>() {
            public Protocal parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Protocal(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Protocal> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Protocal> getParserForType() {
            return PARSER;
        }

        public per.johnson.server.protocal.ProtocalOuterClass.Protocal getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_per_johnson_server_protocal_Protocal_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_per_johnson_server_protocal_Protocal_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016protocal.proto\022\033per.johnson.server.pro" +
                        "tocal\"\177\n\010Protocal\022\016\n\006bridge\030\001 \001(\010\022\014\n\004typ" +
                        "e\030\002 \001(\005\022\023\n\013dataContent\030\003 \001(\t\022\014\n\004from\030\004 \001" +
                        "(\t\022\n\n\002to\030\005 \001(\t\022\n\n\002fp\030\006 \001(\t\022\013\n\003QoS\030\007 \001(\010\022" +
                        "\r\n\005typeu\030\010 \001(\005b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_per_johnson_server_protocal_Protocal_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_per_johnson_server_protocal_Protocal_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_per_johnson_server_protocal_Protocal_descriptor,
                new java.lang.String[] { "Bridge", "Type", "DataContent", "From", "To", "Fp", "QoS", "Typeu", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
